# Generated by Django 2.1.1 on 2018-12-30 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_auto_20181225_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=12, verbose_name='Numero Identificador')),
                ('nombre', models.CharField(max_length=256, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=256, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.SmallIntegerField(blank=True, null=True, verbose_name='Numero de Telefono')),
                ('grupo', models.CharField(blank=True, choices=[('Alumno Duoc UC', 'Alumno Duoc UC'), ('Docente Duoc UC', 'Docente Duoc UC'), ('Administrativo Duoc UC', 'Administrativo Duoc UC'), ('Titulado Duoc UC', 'Titulado Duoc UC'), ('Organizacion Empresarial', 'Organización Empresarial'), ('Comunidad Local', 'Comunidad Local'), ('Organismo Publico', 'Organismo Público'), ('Institucion de Educacion', 'Institución de Educación'), ('Otros', 'Otros')], max_length=255, null=True, verbose_name='Grupo al que pertenece')),
                ('validador', models.BooleanField(default=False, verbose_name='Estado acreditacion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Eventos', to='evento.Evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
                'ordering': ['nombre', 'validador'],
            },
        ),
    ]
