# Generated by Django 2.1.1 on 2018-12-30 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_asistente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Eventos', to='evento.Evento', verbose_name='Evento'),
        ),
    ]
