# Generated by Django 2.1.1 on 2018-12-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_auto_20181229_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='telefono',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de Telefono'),
        ),
    ]
