# Generated by Django 2.1.1 on 2018-12-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_auto_20181229_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='identificador',
            field=models.CharField(max_length=12, unique=True, verbose_name='Numero Identificador'),
        ),
    ]
