# Generated by Django 2.1.1 on 2018-12-30 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_auto_20181229_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Asistentes', to='evento.Evento', verbose_name='Evento'),
        ),
    ]
