# Generated by Django 2.1.1 on 2018-12-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0009_auto_20181230_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='grupo',
            field=models.CharField(blank=True, choices=[('Alumno Duoc UC', 'Alumno Duoc UC'), ('Docente Duoc UC', 'Docente Duoc UC'), ('Administrativo Duoc UC', 'Administrativo Duoc UC'), ('Titulado Duoc UC', 'Titulado Duoc UC'), ('Organizacion Empresarial', 'Organización Empresarial'), ('Comunidad Local', 'Comunidad Local'), ('Organismo Publico', 'Organismo Público'), ('Institucion de Educacion', 'Institución de Educación'), ('Otros', 'Otros')], default='No especificado', max_length=255, null=True, verbose_name='Grupo al que pertenece'),
        ),
    ]
