# Generated by Django 2.1.1 on 2018-12-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0010_auto_20181231_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Numero de Telefono'),
        ),
    ]
