# Generated by Django 2.1.1 on 2018-12-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0011_auto_20181231_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='telefono',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Numero de Telefono'),
        ),
    ]
