# Generated by Django 2.1.1 on 2019-01-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0013_auto_20190103_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inico'),
        ),
    ]
