# Generated by Django 2.1.1 on 2019-01-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0014_auto_20190103_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='ubicacion',
            new_name='direccion',
        ),
    ]
