# Generated by Django 2.1.1 on 2019-01-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0015_auto_20190117_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='lugar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
    ]
