# Generated by Django 2.1.1 on 2019-01-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0016_auto_20190117_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistente',
            name='otro_grupo',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Otro grupo'),
        ),
    ]
