# Generated by Django 2.1.1 on 2019-03-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0017_asistente_otro_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='apellido',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='nombre',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Nombre'),
        ),
    ]
