# Generated by Django 2.1.1 on 2019-04-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0018_auto_20190329_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='area',
            field=models.CharField(blank=True, choices=[('Dirección de Desarrollo Académico', 'Dirección de Desarrollo Académico'), ('Dirección Educación Continua y Online', 'Dirección Educación Continua y Online'), ('Dirección de Docencia', 'Dirección de Docencia'), ('Dirección de Innovación e Investigación Aplicada', 'Dirección de Innovación e Investigación Aplicada'), ('Dirección de Formación General', 'Dirección de Formación General'), ('Dirección de Formación Cristiana y Ética', 'Dirección de Formación Cristiana y Ética'), ('Dirección de Procesos y Tecnologías', 'Dirección de Procesos y Tecnologías'), ('Dirección de Personas', 'Dirección de Personas'), ('Dirección de Gestión y Planificación', 'Dirección de Gestión y Planificación'), ('Dirección de Administración y Finanzas', 'Dirección de Administración y Finanzas'), ('Dirección de Operación y Desarrollo', 'Dirección de Operación y Desarrollo'), ('Dirección de Infraestructura', 'Dirección de Infraestructura'), ('Proyectos y Servicios Duoc UC', 'Proyectos y Servicios Duoc UC'), ('Dirección de Educación Continua y Servicios', 'Dirección de Educación Continua y Servicios'), ('Dirección de Calidad Académica', 'Dirección de Calidad Académica'), ('Dirección de Pastoral', 'Dirección de Procesos de Acreditación'), ('Dirección de Comunicación y Marketing', 'Dirección de Comunicación y Marketing'), ('Dirección de Empleabilidad y Vinculación con el Medio', 'Dirección de Empleabilidad y Vinculación con el Medio'), ('Dirección de Relaciones Internacionales', 'Dirección de Relaciones Internacionales'), ('Dirección de Desarrollo Estudiantil', 'Dirección de Desarrollo Estudiantil'), ('Dirección de Pastoral', 'Dirección de Pastoral'), ('Dirección de Contraloría', 'Dirección de Contraloría')], default='No especificado', max_length=255, null=True, verbose_name='Área organizadora'),
        ),
        migrations.AddField(
            model_name='evento',
            name='escuela',
            field=models.CharField(blank=True, choices=[('Escuela de Administración y Negocios', 'Escuela de Administración y Negocios'), ('Escuela de Comunicación', 'Escuela de Comunicación'), ('Escuela de Construcción', 'Escuela de Construcción'), ('Escuela de Diseño', 'Escuela de Diseño'), ('Escuela de Informática y Telecomunicaciones', 'Escuela de Informática y Telecomunicaciones'), ('Escuela de Ingeniería', 'Escuela de Ingeniería'), ('Escuela de Recursos Naturales', 'Escuela de Recursos Naturales'), ('Escuela de Salud', 'Escuela de Salud'), ('Escuela de Turismo', 'Escuela de Turismo')], default='No especificado', max_length=255, null=True, verbose_name='Escuela organizadora'),
        ),
        migrations.AddField(
            model_name='evento',
            name='sede',
            field=models.CharField(blank=True, choices=[('Campus Arauco', 'Campus Arauco'), ('Alameda', 'Alameda'), ('Antonio Varas', 'Antonio Varas'), ('Maipú', 'Maipú'), ('Melipilla', 'Melipilla'), ('Padre Alonso Ovalle', 'Padre Alonso Ovalle'), ('Plaza Norte', 'Plaza Norte'), ('Plaza Oeste', 'Plaza Oeste'), ('Plaza Vespucio', 'Plaza Vespucio'), ('Puente Alto', 'Puente Alto'), ('San Andrés de Concepción', 'San Andrés de Concepción'), ('San Bernardo', 'San Bernardo'), ('San Carlos de Apoquindo', 'San Carlos de Apoquindo'), ('San Joaquín', 'San Joaquín'), ('Valparaíso', 'Valparaíso'), ('Viña del Mar', 'Viña del Mar'), ('No especificado', 'No especificado')], default='No especificado', max_length=255, null=True, verbose_name='Sede organizadora'),
        ),
    ]
